// Generated by CoffeeScript 1.9.0
(function () {
    $(document).ready(function () {
        return $("#get-trade-analysis-btn").click(function () {
            return $.ajax('trade/' + $('#tradeid').val(), {
                type: 'GET',
                success: function (res, status, xhr) {
                    var parsedTrader = JSON.parse(res).trader;
                    var parsedOfferInfo = JSON.parse(res).tradeOffer;
                    $('.traderinfo #trader-steam-name').html(parsedTrader.steamName);
                    $('.traderinfo #trader-steam-url').html(parsedTrader.steamURL);
                    $('.traderinfo #trader-steam-ava').html(parsedTrader.avatarURL);

                    $('#tradeitemsinfo').html('Revenue = ' + parsedOfferInfo.summDifference + ' $');

                    var table = $('<table/>').appendTo($('#tradeitems-offer'));
                    $(parsedOfferInfo.offering).each(function (i, tradeitem) {
                        $('<tr/>').appendTo(table)
                            .append($('<td/>').text(tradeitem.name))
                            .append($('<td/>').text(tradeitem.price));
                    });

                    table = $('<table/>').appendTo($('#tradeitems-wants'));
                    $(parsedOfferInfo.wants).each(function (i, tradeitem) {
                        $('<tr/>').appendTo(table)
                            .append($('<td/>').text(tradeitem.name))
                            .append($('<td/>').text(tradeitem.price));
                    });
                    alert("Success!");
                    return 0;
                },
                error: function (res, status, xhr) {
                    alert("Error!");
                    return 0;
                }
            });
        });
    });


    /*

     $("main .box-shiny-alt .profilesmall")

     <a href="<!!STEAM-PROFILE>" class="profilesmall">
     <div class="slvl"><!!LEVEL></div>
     <img src="<!!AVATAR>" alt="Avatar"/>
     </a>
     */


    /*

     $("main #tradediv .tradepoll .tradecnt .left/.right .oitm")

     <div class="name">
     <b> Blades of Voth Domosh</b> <br/>
     <span class="hero">Legion Commander</span>'s
     <span class="type">Twin Demon Blades</span>
     <small></small>

     <br><a href="http://steamcommunity.com/market/listings/570/Blades of Voth Domosh">Market</a>
     </div>
     <div class="item  itm559549132">
     <img class="smallimg" src="http://cdn.dota2lounge.com/img/items/5810.jpg" alt="Blades of Voth Domosh"/>
     <div class="rarity Arcana">&nbsp;Arcana&nbsp;</div>
     </div>
     */

}).call(this);
