// Generated by CoffeeScript 1.9.0
(function() {
  $(document).ready(function() {
    return $("#get-trade-analysis-btn").click(function() {
      return $.ajax('trade/' + $('#tradeid').val(), {
        type: 'GET',
        success: function(res, status, xhr) {
          alert('success');
          return 0;
        },
        error: function(res, status, xhr) {
          alert('error');
          return 0;
        }
      });
    });
  });

}).call(this);
